email:
  from: "noreply@test.cider.core.uconn.edu"
  fake:
    enabled: true
    to: ["joseph.oshea@uconn.edu", "ronny.heredia@uconn.edu"]
    whitelist: []

saml:
  idp_metadata: "vendor/engines/saml_authentication/spec/fixtures/idp_metadata.xml"
# paperclip:
#   storage: s3
#   s3_credentials:
#     access_key_id: <%= ENV.fetch("AWS_ACCESS_KEY", Rails.application.secrets.dig(:paperclip, :aws_access_key_id)) %>
#     secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY", Rails.application.secrets.dig(:paperclip, :aws_secret_access_key)) %>
#   s3_region: us-east-1
#   s3_permissions: private
#   bucket: "nucore-staging"
