apiVersion: v1
kind: Service
metadata:
  name: {{ include "nucore.fullname" . }}-nucore
  labels:
    app: {{ include "nucore.name" . }}
    chart: {{ include "nucore.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "nucore.name" . }}
    release: {{ .Release.Name }}
    container: nucore
