apiVersion: v1
kind: Service
metadata:
  name: {{ include "nucore.fullname" . }}-setup
  labels:
    app: {{ include "nucore.name" . }}
    chart: {{ include "nucore.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: setup-talk
      protocol: TCP
      name: setup-talk
  selector:
    app: {{ include "nucore.name" . }}
    release: {{ .Release.Name }}
    container: setup
